name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
          unzip -q android-ndk-r27d-linux.zip
          echo "NDK=$PWD/android-ndk-r27d" >> $GITHUB_ENV

      - name: Compile
        working-directory: ./loader
        run: |
          chmod +x build.sh
          # 把 NDK 路径传给脚本
          export NDK=$PWD/../android-ndk-r27d
          ./build.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libadofailoader
          path: loader/out/libadofailoader.so
